# Generated by Django 3.1.7 on 2021-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('rank', models.IntegerField(max_length=50)),
                ('skill', models.CharField(choices=[('BM', 'BM'), ('BW', 'BW'), ('AR', 'AR')], max_length=20)),
                ('captain', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
