# Generated by Django 3.1.7 on 2021-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
