# Generated by Django 3.1.7 on 2021-10-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20211011_0857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='players',
            new_name='player',
        ),
    ]
