# Generated by Django 3.1.7 on 2021-10-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20211011_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skill',
            field=models.CharField(choices=[('RBM', 'RBM'), ('LBM', 'LBM'), ('BW', 'BW'), ('AR', 'AR')], max_length=20),
        ),
    ]
